version: '3'
services:

  nginx:
    image: tonyyb/laravel-nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    image: tonyyb/laravel-php:7.4
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"

networks:
  app-network:
    driver: bridge